--LOCACAO  -- COD_PRODUTO, QUANTIDADE
-- ESTOQUE -- EST_COD, QTDE


CREATE OR REPLACE TRIGGER BAIXA_ESTOQUE
 AFTER INSERT OR UPDATE OR DELETE OF QUANTIDADE ON LOCACAO
 FOR EACH ROW

  BEGIN
        IF INSERTING THEN     
            UPDATE ESTOQUE SET QTDE = QTDE - :NEW.QUANTIDADE WHERE EST_COD = :NEW.COD_PRODUTO;
        
        ELSIF DELETING THEN        
            UPDATE ESTOQUE SET QTDE = QTDE + :OLD.QUANTIDADE WHERE EST_COD = :OLD.COD_PRODUTO;
        
        ELSIF UPDATING THEN        
            UPDATE ESTOQUE SET QTDE = QTDE + :OLD.QUANTIDADE -- 1º ATUALIZA O VALOR ORIGINAL P/ ANTIGO
            WHERE EST_COD = :OLD.COD_PRODUTO;
           ------------------------------------------------------------------------------------------------ 
            UPDATE ESTOQUE SET QTDE = QTDE - :NEW.QUANTIDADE -- 2º SEGUNDO, ATUALIZA COM O VALOR NOVO...
            WHERE EST_COD = :NEW.COD_PRODUTO;    
        END IF;
  END BAIXA_ESTOQUE;